name: Push images to ECR

on:
  workflow_dispatch:

env:
  AWS_ACCOUNT: 653236170203
  AWS_REGION: ap-southeast-1

permissions:
  id-token: write
  contents: read

jobs:
  push-vote-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Assume ECR Push Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/ECRImagePushRole
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true

      - name: Build vote image
        run: docker build --tag voting-app/vote:${{ github.sha }} ./vote

      - name: Push Vote image to ECR
        uses: jwalton/gh-ecr-push@v2
        with:
          region: ${{ env.AWS_REGION }}
          image: voting-app/vote:${{ github.sha }}

      - name: Download vote current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition voting-app-vote \
            --query taskDefinition \
            > task-definition.json

      - name: Update vote image in task definition
        id: task-def-vote
        env:
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: vote
          image: ${{ env.ECR_REGISTRY }}/voting-app/vote:${{ github.sha }}

      - name: Deploy vote updated task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-vote.outputs.task-definition }}
          service: voting-app-vote
          cluster: voting-app-cluster
          max-retries: 5
          wait-for-service-stability: true

  push-worker-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Assume ECR Push Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/ECRImagePushRole
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true

      - name: Build worker image
        run: docker build --tag voting-app/worker:${{ github.sha }} ./worker

      - name: Push Worker image to ECR
        uses: jwalton/gh-ecr-push@v2
        with:
          region: ${{ env.AWS_REGION }}
          image: voting-app/worker:${{ github.sha }}

      - name: Download worker current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition voting-app-worker \
            --query taskDefinition \
            > task-definition.json

      - name: Update worker image in task definition
        id: task-def-worker
        env:
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: worker
          image: ${{ env.ECR_REGISTRY }}/voting-app/worker:${{ github.sha }}

      - name: Deploy worker updated task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-worker.outputs.task-definition }}
          service: voting-app-worker
          cluster: voting-app-cluster
          max-retries: 5
          wait-for-service-stability: true

  push-result-image-to-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/GitHubActionsOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Assume ECR Push Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/ECRImagePushRole
          aws-region: ${{ env.AWS_REGION }}
          role-chaining: true

      - name: Build result image
        run: docker build --tag voting-app/result:${{ github.sha }} ./result

      - name: Push Result image to ECR
        uses: jwalton/gh-ecr-push@v2
        with:
          region: ${{ env.AWS_REGION }}
          image: voting-app/result:${{ github.sha }}

      - name: Download result current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition voting-app-result \
            --query taskDefinition \
            > task-definition.json

      - name: Update result image in task definition
        id: task-def-result
        env:
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: result
          image: ${{ env.ECR_REGISTRY }}/voting-app/result:${{ github.sha }}

      - name: Deploy result updated task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def-result.outputs.task-definition }}
          service: voting-app-result
          cluster: voting-app-cluster
          max-retries: 5
          wait-for-service-stability: true
