name: Push Vote image to ECR

on:
  workflow_dispatch:

env:
  AWS_ACCOUNT: 653236170203
  AWS_REGION: ap-southeast-1

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::$AWS_ACCOUNT:role/GitHubActionsOIDCRole
          aws-region: $AWS_REGION

      - name: Assume ECR Push Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::$AWS_ACCOUNT:role/CustomElasticContainerRegistryRole
          aws-region: $AWS_REGION

      - name: Push Vote image to ECR
        run: docker build --tag voting-app/vote:v1.0 .
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          region: $AWS_REGION
          image: voting-app/vote:v1.0

      - name: Push Worker image to ECR
        run: docker build --tag voting-app/worker:v1.0 .
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          region: $AWS_REGION
          image: voting-app/worker:v1.0

      - name: Push Result image to ECR
        run: docker build --tag voting-app/result:v1.0 .
        id: ecr
        uses: jwalton/gh-ecr-push@v2
        with:
          region: $AWS_REGION
          image: voting-app/result:v1.0
